version: "2.1"

services:
  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build: ${PROJECT_ROOT}/.docksal/services/cli
    environment:
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
      - SIMPLETEST_BASE_URL=http://${VIRTUAL_HOST}
      - SIMPLETEST_DB=mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-user}@db/${MYSQL_DATABASE:-default}
      - BROWSERTEST_OUTPUT_DIRECTORY=/var/www/${DOCROOT:-docroot}/sites/default/files/simpletest
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}
