#!/usr/bin/env bash

## Runs site initialization
##
## Usage: fin init

# Abort if anything fails
set -e

# Set up paths
DOCROOT_PATH=${PROJECT_ROOT}/${DOCROOT}
SITEDIR_PATH=${DOCROOT_PATH}/sites/default

# Console colors
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Helper functions
echo-yellow () { echo -e "${yellow}$1${NC}"; }

echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"

if [[ ${DOCKER_RUNNING} == "true" ]]; then
	fin reset -f
else
	fin up
fi

echo -e "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"

echo-yellow "Installing composer dependencies..."
cd ${DOCROOT_PATH}
fin composer install

echo-yellow "Making site directory writable..."
chmod 755 ${SITEDIR_PATH}

echo-yellow "Installing drupal..."
DB_URL=mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-user}@db/${MYSQL_DATABASE:-default}
cd ${DOCROOT_PATH}
cp core/phpunit.xml.dist core/phpunit.xml
fin exec drush site-install -y --site-name='Drupal 8' --db-url=${DB_URL}

echo -en "${green_bg} Done ${NC} "
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
exit 0
