#!/usr/bin/env bash

## Runs site initialization
##
## Usage: fin init

# Abort if anything fails
set -e

# Set up paths
DOCROOT_PATH=${PROJECT_ROOT}/${DOCROOT}
SITEDIR_PATH=${DOCROOT_PATH}/sites/default

# Fix fin version
FIN_MIN_VERSION=1.60.0

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Helper functions
echo-red () { echo -e "${red}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Convert version string like 1.2.3 to integer for comparison
# param $1 version string of 3 components max (e.g. 1.10.3)
ver_to_int () {
	echo "$@" | awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
}

if [[ $(ver_to_int $(fin -v)) < $(ver_to_int "${FIN_MIN_VERSION}") ]]; then
	echo-red "Minimal fin version required is: ${FIN_MIN_VERSION}"
	echo -e "Please run ${yellow}fin update${NC} and try again"
	exit 1
fi

echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"

if [[ ${DOCKER_RUNNING} == "true" ]]; then
	fin reset -f
else
	fin up
fi

echo -e "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"

echo-yellow "Installing composer dependencies..."
cd ${DOCROOT_PATH}
fin exec composer install

echo-yellow "Making site directory writable..."
chmod 755 ${SITEDIR_PATH}

echo-yellow "Installing drupal..."
DB_URL=$(fin exec -T printenv SIMPLETEST_DB)
cd ${DOCROOT_PATH}
cp core/phpunit.xml.dist core/phpunit.xml
fin exec drush site-install -y --site-name='Drupal 8' --db-url=${DB_URL}

echo -en "${green_bg} Done ${NC} "
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
exit 0
